### ISSUE TITLE
Wrong version being served on packagist

### ISSUE THREAD

**Issue by syther101** [manuelodelain/linkify-twig-extension#3]
I installed this extension the other day and currently the version which includes whitepace after the closing php tag is being served by packagist. Took my a second the find where the bug was coming from.

Using the latest Symfony 3.4 LTS

Cheers!

p.s. thanks for these little packages you put out @manuelodelain. I actually have your SVG twig extension installed also 😊

**Comment by manuelodelain** [comment]
Thanks for the heads up @syther101 
I will update the package very soon!
